apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logs
spec:
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - mountPath: "/log_data"
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /var/log