apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - mountPath: "/multitool_dir"
              name: common-volume

        - name: busybox
          image: busybox
          command: ['sh', '-c', 'while true; do echo "ping date = $(date)" >> /busybox_dir/date.log; sleep 5; done']
          volumeMounts:
            - mountPath: "/busybox_dir"
              name: common-volume

      volumes:
        - name: common-volume
          emptyDir: {}