#cloud-config
ssh_pwauth: yes
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
chpasswd:
  list: |
    ubuntu:${passwd}
  expire: False
package_update: true
package_upgrade: false
packages:
  - vim
  - nginx
runcmd:
  - echo '<html><img src="http://${bucket}/today.jpg"/></html>' > /var/www/html/index.html