apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ls7
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          volumeMounts:
            - name: index-volume
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
        - name: multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: HTTP_PORT
          ports:
            - containerPort: 81
      volumes:
        - name: index-volume
          configMap:
            name: index-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: ls7
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-multitool
      protocol: TCP
      port: 81
      targetPort: 81
  selector:
    app: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-nginx
  namespace: ls7
data:
  index.html: |
    IT'S MINE NGINX!!!