apiVersion: v1
kind: Service
metadata:
  name: external-svc
spec:
  ports:
    - name: ext-one
      port: 80
      nodePort: 30001
    - name: ext-two
      port: 8080
      nodePort: 30002
  selector:
    app: nginx
  type: NodePort