apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-deployment
  labels:
    app: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      labels:
        app: deploy
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'while true; do echo work >> /tmp/cache/work.log; sleep 5; done']
          volumeMounts:
            - name: my-vol-pvc
              mountPath: /tmp/cache


        - name: network-multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: my-vol-pvc
              mountPath: /static
          env:
            - name: HTTP_PORT
              value: "80"
            - name: HTTPS_PORT
              value: "443"
          ports:
            - containerPort: 80
              name: http-port
            - containerPort: 443
              name: https-port
          resources:
            requests:
              cpu: "1m"
              memory: "20Mi"
            limits:
              cpu: "10m"
              memory: "20Mi"
      volumes:
        - name: my-vol-pvc
          persistentVolumeClaim:
            claimName: pvc-vol